instant commit

diff --git a/bin/git-instant b/bin/git-instant
--- a/bin/git-instant
+++ b/bin/git-instant
@@ -4,13 +4,13 @@
 git rev-parse --is-inside-work-tree &>/dev/null
 
 if [[ $? != 0 ]]; then
-  echo "Not a git repository." 1>&2
+  echo "Error:Not a git repository." 1>&2
   exit 1
 fi
 
 if [ -z "$(git status --porcelain)" ]; then
   # Working directory clean
-  echo "Working directory is clean" 1>&2
+  echo "Error:Working directory is clean" 1>&2
   exit 1
 fi
 
