instant commit for git-instant

diff --git a/bin/git-instant b/bin/git-instant
--- a/bin/git-instant
+++ b/bin/git-instant
@@ -10,7 +10,7 @@ fi
 #confierm working directory
 if [ -z "$(git status --porcelain)" ]; then
   # Working directory clean
-  echo "Error:Working directory is clean" 1>&2
+  echo "git:Error Working directory is clean" 1>&2
   exit 1
 fi
 
@@ -19,7 +19,7 @@ git status
 git add -A
 
 #input commit message
-read -p "commit message:" MSG
+read -p "git:commit message - " MSG
 if [ -z "$MSG" ]; then
     git commit -m "instant commit for git-instant"
 else
